### ISSUE TITLE
Add CPP project

### ISSUE THREAD

**Issue by deepak-chouhan** [GDSC-MITADT-Hacktoberfest2021/Hacktoberfest2021#8]
## Add your CPP projects in `CPP projects` folder

- Your project folder should contain CPP script
- Screenshots of working
- README.md explaining the use of project and requirements

**Comment by deepak-chouhan** [comment]
Sure

**Comment by Yash-RajSingh** [comment]
Hey, I've added one of my projects in the PR #36. Kindly please review it and merge @deepak-chouhan

**Comment by deepak-chouhan** [comment]
@PreetiBaskey You can start contribute, this issue is just for explaining how to contribute
