### ISSUE TITLE
Add Frontend Project

### ISSUE THREAD

**Issue by deepak-chouhan** [GDSC-MITADT-Hacktoberfest2021/Hacktoberfest2021#9]
## Add your FrontEnd projects in `FrontEnd` folder

- Your project folder should contain HTML, CSS, and Java-Script files
- Other external libraries
- Screenshots of webpage
- README.md explaining the project and requirements

**Comment by deepak-chouhan** [comment]
@priyanshu688 Yes, you can fork this repo and add you project folder and make a pull request

**Comment by priyanshu688** [comment]
@deepak-chouhan but you have mentioned that I need to add project in Front-end folder only

**Comment by deepak-chouhan** [comment]
@priyanshu688 Yes, in FrontEnd folder create a seperate folder of your project

**Comment by priyanshu688** [comment]
@deepak-chouhan I have added the project as per your instructions. Please review this PR - https://github.com/GDSC-MITADT-Hacktoberfest2021/Hacktoberfest2021/pull/17

**Comment by priyanshu688** [comment]
@deepak-chouhan please merge this
